### PR TITLE
MES-4164 Modified the query of getNextBatch to handle multiple same appRefs te…

### PR DESCRIPTION
**Pull request by rstepnowski**
…sts conducted by different examiners

# Description and relevant Jira numbers

## Pull Request checklist

- [ ] [WIP] tag removed from PR title
- [ ] PR has an understandable description

## Git feature branch checklist

- [ ] branch name comply with our branching strategy
- [ ] git branch contains relevant JIRA ticket number
- [ ] branch rebased against the latest develop

## Sign off process checklist

- [ ] Code has been tested manually
- [ ] Tested by QA
- [ ] PO's approval
- [ ] Reviewers selected in Github
- [ ] PR link added to JIRA

### CODE REVIEW

**Comment by ammarhaiderbjss** [comment]
Where's this come from? no Jira ref?

**Comment by rstepnowski** [comment]
> Where's this come from? no Jira ref?

It wasn't created at that moment
It's https://jira.dvsacloud.uk/browse/MES-4164

**Review by ammarhaiderbjss — APPROVED** [review]
Happy provided it has been verified in dev

**Review by rossfauldsbjss — APPROVED** [review]
looks good.

**Pull request merged**
